### PR TITLE
Added a Copy button to the parameter panel, that copies current param…

### PR DESCRIPTION
**Pull request by jasonrohrer**
…eters (from adjusted sliders, etc.) to the clipboard as a block of curv parameter code.

### CODE REVIEW

**Comment by doug-moen** [comment]
I like this change. But first I'll mention two problems with the code.
 * `sRGB.HSV[0.456263,0.0322762,0.0322762]` isn't right, because this is an RGB triple, not an HSV triple.
   So you should use `sRGB[0.456263,0.0322762,0.0322762]` instead.
* The code for quoting an identifier containing spaces is not robust, because the identifier could contain arbitrary punctuation characters. Instead of `nameStream << name` use `nameStream << curv::make_symbol(name)` and add `#include <libcurv/symbol.h>` to the top of the source file.

**Comment by jasonrohrer** [comment]
So... if someone specifies an HSV colour in their original .curv file.... this will copy the RGB version of that color to the clipboard, right?  That might be a little bothersome.  Though I suspect that MOST people specify RGB colors, not HSV colours...

One of the great weaknesses of this whole approach is that we don't have any access to the source file, or even the name of the source file, in that part of the code.  So we pretty much know nothing about the original code.

**Comment by jasonrohrer** [comment]
The changes you suggested have been added.

**Comment by doug-moen** [comment]
Thanks for the contribution.

**Pull request merged**
