### PR TITLE
Update all dependencies and GCC-12 support

### PR DESCRIPTION
**Pull request by lf94**
We can now build Curv with latest of its dependencies and using GCC-12. This PR relies on a change that cannot be commit until I have access to curv3d/libfive, because I have a small patch that resides in a branch for that submodule.

https://github.com/curv3d/curv/issues/164 Needs to be fulfilled

### CODE REVIEW

**Comment by doug-moen** [comment]
This is awesome. Thanks very much. Need to look at those failed builds though.

**Comment by doug-moen** [comment]
Something wrong with the ImGUI change:
```
 From https://github.com/ocornut/imgui
   * branch            d73e3285dea2bb352f3a9c0696120091f0b95f0e -> FETCH_HEAD
  Submodule path 'extern/imgui': checked out 'd73e3285dea2bb352f3a9c0696120091f0b95f0e'
  Error: fatal: remote error: upload-pack: not our ref db137dc7af1e157f3184c83f8eb9308441f7f10c
  Error: fatal: Fetched in submodule path 'extern/libfive', but it did not contain db137dc7af1e157f3184c83f8eb9308441f7f10c. Direct fetching of that commit failed.
```

**Comment by lf94** [comment]
Yep! It'll be fixed today :) It was expected but I just wanted you to see the PR was almost ready to go

**Comment by lf94** [comment]
FWIW the actual issue is the libfive dependency. The error output is just weird - working on it now

**Comment by lf94** [comment]
Linux is building, but Windows is failing because of https://github.com/libfive/libfive/issues/522 and mac is failing because of how it uses clang. Trying to fix mac and we'll wait for a response from Matt.

**Comment by doug-moen** [comment]
For the Windows problem, see also https://github.com/libfive/libfive/issues/494

**Comment by doug-moen** [comment]
The `CMakeLists.txt` contains this kludgy and fragile code:
```
if (APPLE)
    # Using Homebrew on macOS. Search /usr/local/include (bug #28) for Intel,
    # or /opt/homebrew for Apple Silicon (bug #128)
    # Also, we now depend on tbb@2020, not tbb, due to openvdb not supporting
    # latest version (June 5 2021).
    include_directories(SYSTEM
    /usr/local/opt/tbb@2020/include /opt/homebrew/opt/tbb@2020/include
    /usr/local/include /opt/homebrew/include)
    link_directories(
    /usr/local/opt/tbb@2020/lib /opt/homebrew/opt/tbb@2020/lib
    /usr/local/lib /opt/homebrew/lib)
endif (APPLE)
```
And it's probably broken again (missing link_directories). I don't know the correct way to write this code.

**Comment by lf94** [comment]
Can we just drop macos? Unless mac and windows users support this, it's not sustainable to keep these custom scripts up to date....

**Comment by doug-moen** [comment]
I originally developed Curv on a Mac. Although that Mac died and I now use a Linux laptop, I can still get access to a Mac. I'm not willing to drop MacOS at this point. We will commit the PR with MacOS broken and I'll investigate the problem afterwards.

**Comment by lf94** [comment]
Fair enough :) I'm trying to get a real GCC running, but AppleClang keeps being picked up:

```
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
```

**Comment by lf94** [comment]
Let's leave the PR open until we can fix these. I think the Windows one is easily fixed with Matt's help. Mac seems to be simple but I'm just fighting with cmake to use gcc. I'll end up doing some custom cmake stuff probably.

**Comment by lf94** [comment]
https://stackoverflow.com/a/50313990 seems promising - trying it out on my lunch break

**Comment by lf94** [comment]
Well I got close in this commit https://github.com/curv3d/curv/pull/165/commits/f08621e9d6caa3140ab87b4feb675b32d5f1c49a but now I'm at a loss again. It can't find some boost header.

**Comment by lf94** [comment]
All right! make test passed :) I've cleaned up the commit history. At this point it's just waiting on libfive for a fix but let's not block ourselves. FWIW It takes almost a full hour to build the mac version. Crazy.

**Comment by doug-moen** [comment]
@lf94 I've updated [libfive 522](https://github.com/libfive/libfive/issues/522) with a specific change that we could make to `libfive/include/libfive/render/brep/default_new_delete.hpp` in order to fix the Windows build. Specifically, change `#if _MSC_VER` to `#ifdef _WIN32`.

**Comment by lf94** [comment]
Nice fix :D

**Comment by doug-moen** [comment]
Wow, we are almost there.
Final step is to make the libfive fix to curv3d/libfive, test it, then send a PR to the libfive project.

**Comment by lf94** [comment]
I'm moving onto the next phase of my "make curv useful to me again" plan: integrating https://github.com/aras-p/glsl-optimizer or building my own optimizer if this fails (which it shouldnt based on my preliminary tests this evening) - I think we should just wait for Matt for the Windows issue. This PR updates our deps so we use libfive/libfive again. I would like to remove curv3d/libfive so we're in-sync with everyone (plus it's just good for the space to know GCC 12 is working with everything)

**Pull request merged**
