### PR TITLE
Add repeat_helix to curv std

### PR DESCRIPTION
**Pull request by zeeyang**
## Justification
`repeat_helix` was listed in the repetition future work section. It's useful for making staircases, chained links, etc. Also remapped `repeat_radial` as `repeat_helix` with step size of 0.

## How to test
```
parametric
    w :: slider[0, 20] = 15;
    dy :: slider[-20, 20] = 6;
    step :: slider[0, 40] = 5;
in
box [5,w,1]
    >> move [0,dy,0]
    >> repeat_helix{reps:12, step:step} 
    >> lipschitz 10
```

Screen Shot 2021-05-01 at 9 02 44 AM

### CODE REVIEW

**Comment by doug-moen** [comment]
Nice addition to Curv!

This definition doesn't make logical sense:
```
repeat_radial reps = repeat_helix{reps:reps, step:0};
```
since `repeat_helix` only works on 3D shapes, and `repeat_radial` is polymorphic between 2D and 3D. According to the documentation, this shouldn't work.

I know you are trying to share code between `repeat_radial` and `repeat_helix`, but I suggest you use separate definitions, then fix `repeat_helix` so that it requires `step > 0` and is 3D only.

I notice the `lipschitz 10` in the example, meaning the distance field isn't very good. I don't know if this can be improved, but that would be another reason for having separate code. There are lots of helix models on shadertoy.com, like this one:
> https://www.shadertoy.com/view/wslBWf

and while I haven't tried reading the code, I bet there is an opportunity to borrow ideas from shadertoy and improve the distance field.

Finally,  I suggest putting the example and the image into the documentation.

**Comment by zeeyang** [comment]
Thanks @doug-moen. The shadertoy link's math does look much simpler. Let me dig into that tonight and restore `repeat_radial`.

I did notice the shape was getting very choppy further away from origin. `lipschitz 10` fixed it but I didn't really understand it. Are the gaps caused by undefined areas in the distance function? I tried `show_gradient` but it didn't yield anything useful.

Screen Shot 2021-05-01 at 3 20 40 PM

**Comment by doug-moen** [comment]
> Are the gaps caused by undefined areas in the distance function?

Here's a quote from docs/Theory.rst:
> According to John C. Hart, author of the original academic papers on SDFs,
the only restriction is that an SDF cannot overestimate the distance from each point to the closest boundary.
In math terms, an SDF must be Lipschitz Continuous, with a Lipschitz constant of 1.
It's a continuous function which is limited in how fast it can change.
For every pair of points in an SDF, the absolute value of the slope of the line connecting
the points is not greater than 1.

The gaps are caused by a bad distance function that overestimates the distance from a point to the surface of the shape. When the distance is overestimated, the Sphere Tracing algorithm used for graphical rendering will skip past the surface of the shape, and a hole appears in the shape.

`lipschitz 10` divides the output of the distance function by 10, which might fix the rendering problem, at least in this case, but also slows down sphere tracing by a factor of 10.

**Comment by zeeyang** [comment]
Cleaned up and closing this for now until I can find a better sdf for helix repeat.

**Pull request closed without merging**
