### PR TITLE
Wordsmith the record comprehensions paragraph

### PR DESCRIPTION
**Pull request by winksaville**
This may not be correct as my understanding is incomplete, but a first
stab. When I do understand I'd also like to provide a series of working
examples that would execute when placed in a file and executed with
`curv -l{e} file.curv`.

Someday it would be great to have a [playground](https://en.wikipedia.org/wiki/Comparison_of_online_source_code_playgrounds) but for now just having working examples that neophytes like me could cut and paste into an editor or otherwise execute would be extremely helpful.

### CODE REVIEW

**Comment by doug-moen** [comment]
I agree that paragraph needs a rewrite. I can't seem to do collaborative editing with you on this paragraph from github (maybe you didn't enable the option that allows me to do this). So I'll merge your change then commit additional changes on top of that.

**Comment by doug-moen** [comment]
With my further edits, the paragraph looks like this:

> Record comprehensions permit you to construct a record value
dynamically. The set of field names is determined at run time using
program logic, which can include if statements, local variables and loops.

> Modules (scoped record constructors) contain a static set of definitions
that form a mutually recursive scope. ...

I'm using the words "dynamic" and "static" to describe the main difference between record comprensions and modules. I think the text is clearer. The following section titled "Record Comprehensions" is the correct place to describe details like the `...` operator.

**Comment by doug-moen** [comment]
Curv does have a playground. Or at least, it has a REPL. Just type "curv" in the shell, with no arguments, and you get an interactive REPL where you can type Curv expressions and see the results. We could add examples to the language documentation of REPL sessions where you type an expression and see the result.

**Comment by doug-moen** [comment]
My plan for the next stage of the Curv user interface is a 3 pane GUI containing a text editor pane, a REPL pane, and a graphics viewer. Perhaps this will feel more like the "playground" that you desire? I don't have a concrete set of requirements for what would constitute a true Curv playground, but maybe you have suggestions. This could also be discussed in a new issue.

**Comment by winksaville** [comment]
I've found it relatively difficult to learn Curv and I think it would be easier to understand and learn if every example was executable. If there was an online playground that would make executing those examples eaiser, but having the executable examples is what I feel would make the learning curve not nearly as steep.

**Pull request merged**
