### PR TITLE
Add soroban example

### PR DESCRIPTION
**Pull request by lf94**
I recreated a soroban example I did in CadQuery. I would like to get some feedback for:

* Where I can reduce code further
* How to fillet both the outside and inside of the frame (maybe even the edges along x and y?)

I believe the soroban is a great example for any Code CAD. It touches a lot while being simple. I think the tutorial should link to it.

### CODE REVIEW

**Comment by lf94** [comment]
I also noticed you cannot use parametric variables in some places, like in `slider` ranges and `local_taper_xy`. Future feature(s)?

**Comment by doug-moen** [comment]
Thanks for the example code! I'll take a closer look after I publish it.

You are right about parametric variables. In principle they should work everywhere, but the implementation involves adding a lot of special case code throughout the interpreter, so I focus on only adding that special case code in the places where it was most useful. I never used parametric variables with `local_taper_xy` in my own code, so that is related to the fact it doesn't work. You can open bug issues if you like, one for each special case. No guarantees of quick fixes right now, since I'm focused on another project right now.

**Comment by doug-moen** [comment]
> How to fillet both the outside and inside of the frame (maybe even the edges along x and y?)

To make a rounded box, you can use `offset`. Try:
```
box >> offset 0.5
```
To create a fillet where two boxes intersect in a union, you can use smooth union. Try:
```
smooth 0.5 .union [box, box >> move[1,1,1]]
```

In general, the code looks reasonable to me.

**Comment by lf94** [comment]
@doug-moen the issue with just using `offset` is that it also increases the whole size of the rectangle? So how can I bring that size back down? Just using `scale` ? Is it accurate to do that?

After a long thinking session last night I believe there is no reason why curv cannot offer a similar API to that of cadquery :slightly_smiling_face: Rather than work with faces though, curv will work with "points" or "origins" (which is what happens anyway at the end of the day in CadQuery).

I'm trying to get a Discord channel up on the Elmer discord server. I'll let you know when / if it gets put up and reply here.

**Comment by doug-moen** [comment]
Try this in the CLI:
```
curv> rounded_box xyz off = box (xyz - 2*off) >> offset off
curv> rounded_box [3,3,3] 0.5
```

**Comment by lf94** [comment]
But what about for an arbitrary shape? Like polygon?

**Comment by lf94** [comment]
I am fairly close to what I want with this, I just need to calculate the `sc` based on the `radius`:

```
let
  fillet radius sc shape = shape >> offset radius >> scale sc;
in
difference [
  fillet 0.0 1.0 (rect [1,1]),
  fillet 1.0 0.25 (rect [0.5, 0.5]),
  //fillet 0.0 1.0 (rect [0.5, 0.5]),
]
```

**Comment by lf94** [comment]
@doug-moen https://discord.gg/9q4AeWvD the channel is "curv3d". Could maybe put it on the google group and the readme?

**Pull request merged**
