### PR TITLE
Add GLTF export support

### PR DESCRIPTION
**Pull request by zeeyang**
Basic GLTF support with embeded base64 buffer. @doug-moen I have very little experience writing C++ so please feel free to nitpick. 

- `$ curv -o shape.gltf -x cylinder`
- drop file into https://gltf-viewer.donmccurdy.com

### CODE REVIEW

**Comment by doug-moen** [comment]
Interesting. What are your goals for adding GLTF support? It's used for 3D graphics, not 3D printing. If we were extending Curv to be used for advanced 3D graphics, then GLTF with PBR (physically based rendering) would be an interesting goal to shoot for. If the goal is advanced 3D printing, then maybe the 3MF file format makes more sense. If you only want to import a plain mesh (no colours or materials) into SceneKit, then any mesh file format will work (eg, see https://github.com/eugenebokhan/asset-import-kit).

I'm okay with accepting this change, but I'd like some more context about where you are heading with your series of pull requests.

**Comment by zeeyang** [comment]
Looks like GLTF is becoming the gateway format for rendering on the web and mobile AR. There are a lot of actively maintained tools and transcoders built around it.

My original goal was to render a curv shape in ARKit which requires USDZ. Since you can losslessly convert GLTF to USDZ, and GLTF has a better ecosystem, I decided to target GLTF.

The immidiate next step is to support material and multiple mesh export. External tools can take care of post-processing (compression, GLB binary encoding, converting to USDZ, etc.)

**Review by doug-moen — CHANGES_REQUESTED** [review]
You can't use `delete [] buff` and then reference `buff` in the next line of code. That is unsafe, undefined behaviour, could cause a crash.

I don't use `new` to allocate memory. A good way to manage this buffer is to allocate it using `std::make_unique` and then let C++ automatically deallocate the memory when it is no longer referenced.

**Comment by doug-moen** [comment]
Your rationale for GLTF sounds good.

As for the future stuff, "The immediate next step is to support material and multiple mesh export."
It would be helpful if you open issues for the next things you want to work on, I can comment, then the issue is marked closed by the commit (using 'fix #ISSUENUM' in the commit message).

**Comment by doug-moen** [comment]
An example of safe buffer allocation:
```
auto buf = std::make_unique<char[]>(nchars);
```

**Comment by zeeyang** [comment]
> It would be helpful if you open issues for the next things you want to work on

My bad I should have filed an issue before starting this. Definitely will do that in the future so there's no surprises.

> A good way to manage this buffer is to allocate it using std::make_unique

Thanks I didn't know about smart pointers. Just pushed up a fix.

**Pull request merged**
