### PR TITLE
Added AppImage build workflow

### PR DESCRIPTION
**Pull request by A-G-D**
- Added:
  - `linux-build` action to github actions
  - `build-appimage.sh` - AppImage builder script
  - `AppRun` - Entry point for AppImage execution (required by AppImage spec)
  - `icon.curv` - will be exported to png (icon required by AppImage spec)

### CODE REVIEW

**Comment by doug-moen** [comment]
Very cool. The `icon.curv` is a nice touch.

**Comment by doug-moen** [comment]
AppImages are supposed to be self-contained universal executables, so I tested it on a Ubuntu 18.04 system, where it should work, even though the system is out of date. But I got the following error message:
```
$ ./curv-x86_64.AppImage 
curv: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by curv)
curv: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by curv)
```

**Comment by doug-moen** [comment]
troubleshooting:
```
$ ./curv-x86_64.AppImage --appimage-extract
$ ldd squashfs-root/usr/bin/curv
squashfs-root/usr/bin/curv: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by squashfs-root/usr/bin/curv)
squashfs-root/usr/bin/curv: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by squashfs-root/usr/bin/curv)
	linux-vdso.so.1 (0x00007ffcd0344000)
	libboost_iostreams.so.1.71.0 => /home/doug/Downloads/curv/squashfs-root/usr/bin/../lib/libboost_iostreams.so.1.71.0 (0x00007f4c4f509000)
	libboost_filesystem.so.1.71.0 => /home/doug/Downloads/curv/squashfs-root/usr/bin/../lib/libboost_filesystem.so.1.71.0 (0x00007f4c4f4e7000)
	libtbb.so.2 => /home/doug/Downloads/curv/squashfs-root/usr/bin/../lib/libtbb.so.2 (0x00007f4c4f49c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4c44feb000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4c44de7000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f4c44aaf000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4c44726000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4c44388000)
	libgomp.so.1 => /home/doug/Downloads/curv/squashfs-root/usr/bin/../lib/libgomp.so.1 (0x00007f4c4f42d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4c44170000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4c43d7f000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4c43b62000)
	libbz2.so.1.0 => /home/doug/Downloads/curv/squashfs-root/usr/bin/../lib/libbz2.so.1.0 (0x00007f4c4f417000)
	liblzma.so.5 => /home/doug/Downloads/curv/squashfs-root/usr/bin/../lib/liblzma.so.5 (0x00007f4c4f3ed000)
	libzstd.so.1 => /home/doug/Downloads/curv/squashfs-root/usr/bin/../lib/libzstd.so.1 (0x00007f4c4f342000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4c4f311000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f4c4393a000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f4c43736000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f4c43530000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f4c4331b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4c43113000)
```

Although I'm not an expert, it appears there are some dependencies missing from the AppImage:
```
/lib64/ld-linux-x86-64.so.2
/lib/x86_64-linux-gnu/libbsd.so.0
/lib/x86_64-linux-gnu/libc.so.6
/lib/x86_64-linux-gnu/libdl.so.2 
/lib/x86_64-linux-gnu/libgcc_s.so.1
/lib/x86_64-linux-gnu/libm.so.6
/lib/x86_64-linux-gnu/libpthread.so.0
/lib/x86_64-linux-gnu/librt.so.1
/lib/x86_64-linux-gnu/libz.so.1 
linux-vdso.so.1
/usr/lib/x86_64-linux-gnu/libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libX11.so.6 
/usr/lib/x86_64-linux-gnu/libXau.so.6 
/usr/lib/x86_64-linux-gnu/libxcb.so.1
/usr/lib/x86_64-linux-gnu/libXdmcp.so.6
```

**Comment by A-G-D** [comment]
It seems the linuxdeploy tool (which is the official tool provided by the AppImage format creators) excludes by default all libraries that are part of glibc, as well as other common libraries ('minimal set of libraries that are expected to be part of host system' as they put it). [Here](https://github.com/AppImage/pkg2appimage/blob/master/excludelist) they provide the list of libraries that should not be bundled when creating an AppImage package.

But I guess it also makes sense to bundle them in this case since the required glibc version is quite new, which may not be available on older distros that still have LTS. I'll see if there is an option (or another tool) to include ALL dependencies.

**Comment by doug-moen** [comment]
The AppImage works on Fedora. I withdraw my objection that it doesn't work on Ubuntu 18.04. Fixing this does not seem like a good use of time. Rationale below.

-----------------------------------------------------------
In general, it seems that bundling the dynamic linker and glibc doesn't work, which is why there is an excludelist. In the case of Curv, it can't be statically linked, because it must use the system dynamic linker to load: the OpenGL driver (which is GPU specific and can't be bundled), and .so files created by the C++ compiler when using the -Ojit option for exporting mesh files.

I tried running the January 2021 appimage of OpenSCAD on my Ubuntu 18.04 system, and it works. OpenSCAD uses OpenGL, so it has similar runtime requirements as Curv. From here: https://files.openscad.org/OpenSCAD-2021.01-x86_64.AppImage

All of the dependencies that are not bundled by Curv are also not bundled by OpenSCAD. In fact OpenSCAD has a larger list of unbunded dependencies. So bundling more libraries is not the solution.

Is Curv bundling something it shouldn't? Curv statically links most of its dependencies because in the past, this has been the best way to avoid "dependency hell" on Mac/Windows/Linux. The 3rd party libraries provided by the distro (such as OpenVDB or ImGui) are sometimes not API compatible with Curv, since these libraries may have incompatible APIs across different versions.

It looks like one of Curv's statically linked library dependencies is relying on glibc/glibc++ symbols in the build system (Ubuntu 20.04?) that are not present in the same libraries on Ubuntu 18.04.

I think this is a general problem with AppImage. It is not a "build once run anywhere" system. AppImages only work on "sufficiently recent" versions of "major" distros. I am thinking it is a waste of time to fix this problem with Ubuntu 18.04 because it isn't feasible to make a Curv appimage work on all Linux systems anyway. The solution is to upgrade your Ubuntu system or build your own binary.

I think that the AppImage model is kind of broken, and that a "build once run anywhere" app distribution format needs to provide a standard runtime interface that is ported to each Linux distro. Flatpak meets this requirement. For example, it seems likely that a Curv AppImage will never run on Alpine Linux due to the fact that Alpine uses musl libc instead of glibc. The Alpine docs recommend Flatpak as the best way to run glibc GUI programs.

**Comment by doug-moen** [comment]
Thanks for your awesome contribution!

**Comment by A-G-D** [comment]
Thanks for the info. In that case, I might just work on making the current AppImage updatable and provide the other needed metadata.

```
I think that the AppImage model is kind of broken, and that a "build once run anywhere" app distribution format needs to provide a standard runtime interface that is ported to each Linux distro. Flatpak meets this requirement. For example, it seems likely that a Curv AppImage will never run on Alpine Linux due to the fact that Alpine uses musl libc instead of glibc. The Alpine docs recommend Flatpak as the best way to run glibc GUI programs.
```
On the bright side, I read some guys in the AppImage team planning to do something like this and provide a runtime for type 3 (which would replace the current type 2 image format) AppImages, as well as address the issues of current AppImage standard, though I don't think they're focusing their heavy attention to it yet. And I just forgot the link to that thread.

**Comment by doug-moen** [comment]
Once you are done with your AppImage work, I'll make a release and upload the appimage to the release, as per issue https://github.com/curv3d/curv/issues/134

**Pull request merged**
