### PR TITLE
Export GPU program as JSON

### PR DESCRIPTION
**Pull request by zeeyang**
Export program as json: `curv -o test.jgpu example.curv`. See discussion https://github.com/curv3d/curv/discussions/114

### CODE REVIEW

**Comment by doug-moen** [comment]
Hi @zeeyang 
I would like you to not modify the export_json() function, because that has an existing purpose, it is used for exporting arbitrary Curv values in JSON format.

Instead, I would like you to use a new file extension, I'm suggesting it should be `*.jgpu`. So you will add a new function called `export_jgpu`, which is a modified version of the existing `export_gpu` function. You will add a new entry to the `exporters` table, which will be a modified version of the existing entry for `"gpu"`.

**Comment by zeeyang** [comment]
Sure thing. Amended commit as `curv -o jpgu xx.curv`.

When I tried the default JSON export it printed mostly `<function>` stubs (see below), which is not very useful. I'm curious how would I go about "exporting arbitrary Curv values".

``` json
{"argument":{"r":3.141592653589793},"bbox":[[-8.95342712474619,-8.95342712474619,-1.5392135623730963],[20.95342712474619,8.95342712474619,1.5392135623730963]],"call":"<function>","colour":"<function>","dist":"<function>","is_2d":false,"is_3d":true}
```

**Comment by doug-moen** [comment]
> I'm curious how would I go about "exporting arbitrary Curv values".

Try these commands from the shell:
```
$ curv -o json -x 2+2
4
$ curv -o json -x 1..3
[1,2,3]
$ curv -o json -x '{a:1,b:2}'
{"a":1,"b":2}
```
The input is Curv values representing pure data (no functions), the output is valid JSON.

**Comment by doug-moen** [comment]
If you try to export a shape as JSON, the results are useless. The results could be more useful in the future (in the next major language revision); I'd like the output to look more like an OpenSCAD CSG tree. For now, the purpose is to export model parameters as JSON.

**Comment by doug-moen** [comment]
Thanks for the change. It looks good. I'll run some tests.

**Comment by doug-moen** [comment]
Works for me.

**Pull request merged**
